name: .NET

on:
  push:
    branches: [ master,mihir-gautam-patch-1 ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: ./Webgentle.BookStore
      run: dotnet restore
    - name: Build
      working-directory: ./Webgentle.BookStore
      run: dotnet build **/*.csproj --configuration Release
    - name: Publish
      working-directory: ./Webgentle.BookStore
      run: dotnet publish -r win10-x64 --configuration "Release" --self-contained "true" -o ../site
    - name: Generate deployment package 
      working-directory: ./Webgentle.BookStore
      run: zip ../site.zip *; cd ..; zip myapp.zip site.zip aws-windows-deployment-manifest.json
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyProject
        path: Webgentle.BookStore/myapp.zip
    
    - name: Deploy to AWS Beanstack
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: myapplication
        environment_name: myenvironment
        version_label: ${{ github.run_id }}
        region: us-west-2
        deployment_package: myapp.zip
      
